language: java
jdk:
- oraclejdk13
addons:
  chrome: stable
install: 
    - wget -N http://chromedriver.storage.googleapis.com/2.43/chromedriver_linux64.zip -P ~/
    - unzip ~/chromedriver_linux64.zip -d ~/
    - rm ~/chromedriver_linux64.zip
    - sudo mv -f ~/chromedriver /usr/local/share/
    - sudo chmod +x /usr/local/share/chromedriver
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
