language: java
jdk:
- oraclejdk13
addons:
  chrome: stable
install: # Install ChromeDriver (64bits; replace 64 with 32 for 32bits).
- wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
- unzip ~/chromedriver_linux64.zip -d ~/
- rm ~/chromedriver_linux64.zip
- sudo mv -f ~/chromedriver /usr/local/share/
- sudo chmod +x /usr/local/share/chromedriver
- sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
install: mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
